### PR TITLE
Add furlong

### LINKED ISSUE #7: Convert furlong to metric distance
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

Furlongs should be converted to metric distances (meters, km, etc.)

See [this commit](../commit/e0eb7f637d8703c9251de70794d117438f9d8fe1) for an example of how to add a new conversion

### PR DESCRIPTION
**Pull request by esclear**
1 fur = 201.168 m

[finish #150135802]

Closes #7

### CODE REVIEW

**Comment by esclear** [comment]
Aww, right.
The other commits are being included here anyway.

**Comment by cannawen** [comment]
Awesome, this looks great! 

Really stupid technicality, but in the [Hacktoberfest rules](https://hacktoberfest.digitalocean.com/) it says you need to make 4 PRs between Oct 1-31 to get the T-shirt, and it's still September... do you want to re-submit the PR in October for it to count towards the contest?

**Comment by esclear** [comment]
Nah, you may just as well merge it.

There ist still the litres to m^3 change in here, shall I rebase and exclude it?

**Comment by cannawen** [comment]
Oh yeah, can you make a separate PR for the m^3 change and add a test for it? :) 

Thank you so much for taking the initiative to add that, it's a really good idea!

**Comment by esclear** [comment]
The m^3 change is removed here for now.

**Comment by cannawen** [comment]
[Deployed the code to v0.11.1!](https://www.reddit.com/r/test/comments/730lso/metric_units_testing/) Feel free to spam all subreddits with furlong measurements now :P

Note: It won't always trigger on comments, but that's a different bug with polling the reddit comments that I need to fix... haha

**Pull request merged**
