### PR TITLE
Issue 64: Generate TOC for markdown files

### PR DESCRIPTION
**Pull request by cpa5399**
Relevant to this issue: https://github.com/cannawen/metric_units_reddit_bot/issues/64
Generated a table of contents for the two markdown files in this project. 

Todo:
- [x] - Tests pass
- [ ] - Update documentation on how to use the doctoc tool whenever markdown files are changed

### CODE REVIEW

**Review by cannawen — CHANGES_REQUESTED** [review]
Hey, this looks great so far! The contributing and readme have changed, so now there are conflicts with the main repo :( 

But I guess the conflicts are helpful in a way, so you can document the steps for how to auto-generate the tables ;)

**Comment by cpa5399** [comment]
@cannawen Awesome! I'll work on those changes soon!

**Comment by nalinbhardwaj** [comment]
@cpa5399 ping. Do you need any help fixing the conflicts?

**Comment by cannawen** [comment]
Closing due to inactivity - Perhaps a future enhancement to look into.

**Comment by nalinbhardwaj** [comment]
@cannawen since this is mostly done and not a lot of further work is needed here, I can finish off the work here if that's fine?

**Comment by cannawen** [comment]
@nalinbhardwaj We need to add some documentation on how to "refresh" the TOC when the docs get updated. You can look into it after #116 is finished if you want :) It would be a useful thing to have

**Pull request closed without merging**
