### PR TITLE
Add test coverage statistics

### LINKED ISSUE #56: Add test coverage statistics to repository
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

**Enhancement request:**
Investigate how to get test coverage data into the README.md file. 
One possible solution is to use [Coveralls](https://coveralls.io/). Any other suggestions are welcome.

**Recommended reading:**
[CONTRIBUTING.md](https://github.com/cannawen/metric_units_reddit_bot/blob/master/CONTRIBUTING.md) (sections "Etiquette", "Work on an issue" and "Make a PR" are most important)

**Estimated effort:** 
30-60 minutes

# Comment below if you would like to take on this task!

### PR DESCRIPTION
**Pull request by chazzlabs**
## PR Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cannawen/metric_units_reddit_bot/blob/master/CONTRIBUTING.md)
- [x] New functionality (or bug fix) is appropriately tested
- [x] PR includes `closes #{issue number}` if appropriate

## Brief description of changes:

Added Coveralls code coverage.  A new npm script, `cover`, was added which runs Istanbul on the results of the Mocha unit test runner and generates coverage reports.  This script is run after a successful TravisCI build, and results are reported by Coveralls.

## Relevant link(s):

Resolves #56.

### CODE REVIEW

**Review by cannawen — APPROVED** [review]
This looks good! There are conflicts though :( Can you rebase and merge this into master after #97 is merged in?

**Comment by chazzlabs** [comment]
@cannawen This should be good to go now.  And it looks like the coverage went up! 😄

**Comment by cannawen** [comment]
I'm a bit confused with the "files changed", it looks like somehow a bunch of other commits got into PR ... uhhh.... any idea how to fix it? If we squash-merge the PR in, would it look ok on master?

**Comment by chazzlabs** [comment]
@cannawen  That's strange.  Could it be because I did a `git rebase`?  If you look at the commits in this PR it also lists all of my relevant commits twice which also confuses me.  I'm not sure about the squash merge suggestion; I've never used squash before.

**Comment by nalinbhardwaj** [comment]
Better to fast forward the branch first to prevent unwanted changes. @cannawen

**Comment by cannawen** [comment]
Maybe this will fix it @chazzlabs?

Check out your `master` branch
`git reset --soft cf369d6`
make a branch
`git commit -m "Add test coverage statistics"`
make sure the commit looks ok and you haven't lost any code
`git push -u origin branch`
make a PR of that branch

There's also probably some `rebase -i` solution but interactive rebases confuse me :rofl:

**Pull request closed without merging**
