### PR TITLE
Closes issue#79

### LINKED ISSUE #79: "oz" is not being converted to "troy oz" in subreddit /r/Pmsforsale
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

## First timers only
This issue is reserved for anyone who has **never** made a pull request to Open Source Software. If you are not a first timer, we would still love your help! Please see our other open issues :) 

[Read our New to OSS guide](https://github.com/cannawen/metric_units_reddit_bot/blob/master/NEW-TO-OSS.md) for an overview of what to expect
### IMPORTANT: Comment below if you would like to volunteer to fix this bug.

---

## Recommended experience
- Programming fundamentals (`if` statements, arrays, etc.)
- No previous experience working with Regular Expressions
- Some familiarity with how Reddit works

## Time estimate
30-60 minutes

## Background Information
So, you want to work on a Reddit bot that converts imperial units to metric units? Awesome! It's not an easy problem to solve though :( Imperial units are confusing!!

Take ounces, for example. When someone says "ounces" they usually mean [regular ("avoirdupois") ounces](https://en.wikipedia.org/wiki/Avoirdupois) (which is 28.3495 grams). But, they could also be referring to ["troy" ounces](https://en.wikipedia.org/wiki/Troy_weight) (31.1035 grams). Troy ounces are most often used when dealing with precious metals, like gold or silver

## The problem
The subreddit [/r/Pmsforsale](https://www.reddit.com/r/Pmsforsale/) is all about precious metals. They may refer to something as "ounce", but what they really mean is "troy ounce"

So, when the bot finds itself in /r/Pmsforsale, we want it to find all mentions of "ounces" and replace them with "troy ounces". This should already be happening, but it is not! There is a bug in the code.

To replace "ounces" with "troy ounces", we must find them by using a thing called Regular Expressions (also known as a, "regex"). Regexes help us find strings that match a certain pattern. For example if we had a regex `a` and applied it to this string: `ababcA` ... it would find all of the lower case a's but ignore the other characters (b, c, and A).  
OPTIONAL: You can go through [this tutorial](https://regex101.com/) to learn more about regexes

OK, we are ready to get started. Lets get our development environment set up!

If you run into any problems, try googling for a solution. If that doesn't work, reply to this issue with screenshots of the error and what steps you have already taken to try to solve the problem. We're happy to help :) 

1. Open up a terminal window and type `node --version`
2. If it complains you do not have node, download it [here](https://nodejs.org/en/download/). 
3. If your Node version is under v6.2.1, you have to update it
4. Fork the main github repository and "clone your fork" (download the bot's code) using git. [See more detailed instructions here](https://guides.github.com/activities/forking/)
5. Run `npm install` to download all of the required dependencies
6. Run `npm test` to run all of the tests. All green? Yay!
7. Open `./src/conversion_helper-test.js` in your favourite text editor
8. Search for the text "should convert oz to troy oz in precious metal sub"
9. Replace `it.skip` with `it.only`. This will tell the program to only run this single test. While you're here, take a look at the test! Read it carefully, can you guess what it does?
10. Run `npm test` again
11. Observe failing test :( Boo, failing tests! Booo! Tests allow us to define inputs and expected outputs to functions, so we can see if a function is doing the correct thing.
12. This test is failing because of a bug in the code. Let's go find that code
13. Go to `./src/conversion_helper.js` and find where we declare `specialSubredditsRegex`
14. This line creates a regex, but all regexes are case-sensitive by default! Notice the difference in capitalization in our test vs. our regular expression?
15. Your task is to make the regex match case-insensitively to make the test pass. Please use Google or any other resource.   
OPTIONAL: Can you think of other ways to make the test pass? Post your ideas in your Pull Request description later on (step 18).
16. Once your single test is passing, change the `it.only` to `it` to run all of the tests again.
17. Is everything green? Woohoo, green! Yay!!
18. Please commit the changes with a descriptive git commit message, and then make a pull request back to the main repository :)  
OPTIONAL: Don't forget to [give yourself credit](https://github.com/cannawen/metric_units_reddit_bot/blob/master/CONTRIBUTING.md#add-yourself-to-the-contributors-list)! Thank you for contributing to metric_units bot! 
19. Wait for your PR to be reviewed by a maintainer, and address any comments they may have

## Step 20: YOUR CHANGE GETS MERGED AND RELEASED!! Party!!!

### PR DESCRIPTION
**Pull request by namantw**
## PR Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cannawen/metric_units_reddit_bot/blob/master/CONTRIBUTING.md)
- [x] New functionality (or bug fix) is appropriately tested
- [x] PR includes `closes #79` if appropriate

## Brief description of changes:

Added a flag 'gi' in line 375 so that regular expression ignores the cases.

## Relevant link(s):
closes #79

### CODE REVIEW

**Review by cannawen — CHANGES_REQUESTED** [review]
Hey @namantw the code changes look great!

Some feedback about the actual PR:
- For the check boxes, if you remove the space before the x (so turn [ x] into [x]), it will format nicer and look like a checked off box 
- I see you have made a comment describing your PR! Can you also add that same comment to the PR description? This way, all the important information is at the top for future contributors to see :)
- Can you add the line "closes {issue number}" to below the section where it says "relevant links"?

**Comment by namantw** [comment]
Hey @cannawen I have corrected the errors in PR.

**Comment by cannawen** [comment]
Cool, thanks for the changes! 

One small note: 

The reason it's generally good practise to included "close {issue number}" is so that github automagically closes the linked issue. [See this PR for example](https://github.com/cannawen/metric_units_reddit_bot/pull/75), if you hover over the word "closes" with your mouse, github gives you a popup saying that the issue will be closed once the PR is merged in. 

Can you change your description to say "closes #79" (without the word "issue")? It seems very pedantic I know, but it helps keep the PRs and Issues linked in an open source project :)

**Comment by namantw** [comment]
It is amazing that I got to learn so much from my first PR, all thanks to you :)
@cannawen I have corrected it :)

**Review by cannawen — APPROVED** [review]

**Comment by cannawen** [comment]
Yay, I'm glad you found the experience a positive one! Thank you for contributing :D 

Your fix will be in the v0.11.9 release, and I will add you to the "contributors" grid shortly.

**Pull request merged**
