### PR TITLE
Add personality response for 'I would walk 500 miles'

### LINKED ISSUE #65: Personality response for "I would walk 500 miles"
When the bot sees "I would walk 500 miles" it should respond "And I would walk 804.672km more" (or other similar joke responses)

This is more complex than adding a standard personality, because this relies on new comments and not comment replies.

### PR DESCRIPTION
**Pull request by sirugh**
## PR Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cannawen/metric_units_reddit_bot/blob/master/CONTRIBUTING.md)
- [x] New functionality (or bug fix) is appropriately tested
- [x] PR includes `closes #{issue number}` if appropriate

## Brief description of changes:

Adds the desired response to the robot reply section of the personality module.

## Relevant link(s):

closes #65

### CODE REVIEW

**Comment by cannawen** [comment]
Hey @sirugh ! Thank you for the PR :) This one is tricky, there is actually more to do than just adding the response to personality.js 

The responses in personality.js are triggered upon reading a private message, but the "I would walk 500 miles" is more like a conversion, in which it's triggered by searching through all new comments. It should be programmed more like the "totallynotrobots" special case in `bot.js`.

I'm going to close this PR. But I can assign #65 to you, if you be interested in adding the special case to bot.js? We would be eternally grateful :D

**Comment by sirugh** [comment]
Sure I can do that, thanks for the pointer!

**Comment by sirugh** [comment]
@cannawen after looking into it, the case for totallynotrobots is a bit confusing. In fact, if you look [here](https://github.com/cannawen/metric_units_reddit_bot/blob/master/src/bot.js#L84-L96) it looks like the bot actually determines the personality response based on the incoming comment (to match a regex). The totallynotrobots case occurs immediately below it, but it only checks for messages in that specific subreddit.

What I'm trying to say is that my changes from this PR *should* have worked as intended. An incoming message to the bot would have passed through the logic I linked, thus creating the intended response.

**Comment by cannawen** [comment]
@sirugh You're correct, it's not exactly like totallynotrobots, sorry for being unclear!

We want to search new comments for "I would walk 500 miles" which is going to come from the network call `network.getRedditComments("all")` (in `postConversions` function), and not `network.getUnreadMessages();`

I think it would make sense to rename `postConversions` to `handleNewComments` (or similar) and then add the 500-mile code in there, before we check for what conversions exist. What do you think?

**Comment by cannawen** [comment]
Also FYI, a PR was just merged into master that makes some heavy bot.js changes, so it would make sense to pull down the latest code

**Pull request closed without merging**
